# fly.toml app configuration file generated for studentiunisannio1991 on 2025-06-10T23:26:46+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'studentiunisannio1991'
primary_region = 'fra' # O la tua regione corretta (es. 'fra' per Francoforte)

[build]
  builder = "paketobuildpacks/builder:base" # Usa il builder Paketo base
  # La sezione [build.args] non è necessaria per le variabili d'ambiente
  # runtime, verranno caricate dai segreti di Fly.io. Puoi rimuoverla.

# SEZIONE: Variabili d'ambiente per l'applicazione
[env]
  PORT = "8080" # Imposta la porta per Gunicorn

# --- NUOVA SEZIONE: COMANDO DI DEPLOY ---
# Questa sezione definisce un comando che viene eseguito UNA SOLA VOLTA
# ogni volta che fai un nuovo deploy, prima che l'app venga avviata.
# È il posto perfetto per inizializzare o migrare il database.
[deploy]
  release_command = "python init_db.py"

# SEZIONE: Definisce come Fly.io deve avviare i processi
[processes]
  web = "gunicorn --bind 0.0.0.0:$PORT app:app" # Processo web definito

[http_service]
  internal_port = 8080 # Questa è la porta interna della VM
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['web'] # Punta al processo 'web' definito

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1