# fly.toml app configuration file
# App Name e Regione Principale
app = 'studentiunisannio1991'
primary_region = 'fra'

# Sezione di Build. Specifica solo il builder, nient'altro.
[build]
  builder = "paketobuildpacks/builder:base"

# Sezione di Deploy. Questo comando viene eseguito ad ogni deploy.
[deploy]
  release_command = "python3 init_db.py"

# Variabili d'ambiente per l'app in esecuzione.
[env]
  PORT = "8080"

# Configurazione del servizio HTTP.
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['web']

# Definizione dei processi che l'app può eseguire.
[processes]
  web = "gunicorn --bind 0.0.0.0:$PORT app:app"

# Configurazione della macchina virtuale.
[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1