# fly.toml app configuration file
# ... (app, primary_region, [build]) ...

# SEZIONE NUOVA/MODIFICATA: Variabili d'ambiente per l'applicazione
[env]
  PORT = "8080" # <-- AGGIUNGI QUESTA SEZIONE E RIGA!

[processes]
  web = "gunicorn --bind 0.0.0.0:$PORT app:app" 


[http_service]
  internal_port = 8080 # Questa è la porta interna della VM
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['web'] 


[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1