# fly.toml app configuration file generated for studentiunisannio1991 on 2025-06-10T23:26:46+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'studentiunisannio1991'
primary_region = 'fra' # O la tua regione corretta (es. 'fra' per Francoforte)

[build]
  builder = "heroku/buildpacks:20" # <-- MODIFICATO: Usa il builder Heroku per maggiore compatibilità
  # Aggiungi questa sezione per passare DATABASE_URL al processo di build
  [build.args]
    DATABASE_URL = "postgres://postgres:k8OAWsfTNiwoQ4n@polished-night-1030.flycast:5432"
    # SOSTITUISCI L'INTERA STRINGA con quella ESATTA del tuo database PostgreSQL
    # (inclusa la password che ti è stata data da flyctl postgres create)


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1