app = 'studentiunisannio1991'
primary_region = 'fra'

[build]
  builder = "paketobuildpacks/builder:base" # Usa il builder Paketo base
 
[env]
  PORT = "8080"

[processes]
  web = "gunicorn --bind 0.0.0.0:$PORT app:app"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['web'] 

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1