# fly.toml app configuration file generated for studentiunisannio1991 on 2025-06-10T23:26:46+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'studentiunisannio1991'
primary_region = 'fra'

[build]
# fly.toml
app = "studentiunisannio1991" # Il nome della tua app su Fly.io (dovrebbe già essere qui)
primary_region = "fra" # La regione della tua app (dovrebbe già essere qui)

[build]
  builder = "paketobuildpacks/builder-python" # Questo potrebbe essere diverso, controlla la tua riga [build] esistente
  # Aggiungi questa sezione per passare DATABASE_URL al processo di build
  [build.args]
    DATABASE_URL = "postgres://postgres:k8OAWsfTNiwoQ4n@polished-night-1030.flycast:5432"


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
